### ISSUE TITLE
Not related but just curious for you to see this

### ISSUE THREAD

**Issue by furtabs** [r52/gcadapter64#1]
Care fixing that google drive link for op64 since boost is giving me a nightmare I’m trying to compile your GC plugin

**Comment by r52** [comment]
This plugin never required op64 to compile in the first place. The solution file that came with this repo was set up for a standalone compile. 

Regardless I took the time to refresh the code base for VS2017/new library versions, backport fixes from Dolphin, and fix some issues with usage in PJ64. I also set up a [build bot](https://ci.appveyor.com/project/r52/gcadapter64) for this project so you can grab PJ64 compatible builds from there.

A warning however, I don't have quick access to an adapter for testing anymore so all of this stuff is completely untested. On top of that, I consider this plugin mostly complete so support from me going forward is going to be minimal or nonexistent.

Have fun
